services:
  - type: web
    name: spring-boot-render
    runtime: java
    buildCommand: |
      chmod +x gradlew
      ./gradlew clean bootJar
    startCommand: java -jar build/libs/app.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        value: your-postgres-host-from-render
      - key: DB_NAME
        value: your-database-name
      - key: DB_USERNAME
        value: your-database-username
      - key: DB_PASSWORD
        value: your-database-password
      - key: PORT
        value: 8080
    plan: free