services:
  - type: web
    name: springboot-user-api
    runtime: node  # We're using Node environment but overriding everything
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/app.jar
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: mydb
          property: host
      - key: DB_NAME
        fromDatabase:
          name: mydb
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mydb
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mydb
          property: password