services:
  - type: web
    name: springboot-api
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y openjdk-17-jdk
      ./gradlew build
      # Find and store Java location
      JAVA_PATH=$(update-alternatives --list java | head -1)
      echo "Found Java at: $JAVA_PATH"
      echo "export JAVA_PATH='$JAVA_PATH'" >> /etc/profile.d/java.sh
    startCommand: |
      source /etc/profile.d/java.sh
      "$JAVA_PATH" -jar build/libs/app.jar