databases:
  - name: mydb
    databaseName: mydb
    user: myuser
    plan: free

services:
  - type: web
    name: springboot-api
    runtime: python  # We'll use Python but override everything
    buildCommand: |
      curl -s "https://get.sdkman.io" | bash
      source "$HOME/.sdkman/bin/sdkman-init.sh"
      sdk install java 17.0.8-tem
      ./gradlew build
    startCommand: |
      source "$HOME/.sdkman/bin/sdkman-init.sh"
      java -jar build/libs/app.jar
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: mydb
          property: host
      - key: DB_NAME
        fromDatabase:
          name: mydb
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mydb
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mydb
          property: password