services:
  - type: web
    name: springboot-api
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/your-app-name.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: springboot-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: springboot-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: springboot-db
          property: password

databases:
  - name: springboot-db
    databaseName: mydb
    user: admin
